# Generated by Django 3.2.4 on 2022-12-23 13:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('year', django.db.models.manager.Manager()),
            ],
        ),
    ]
